'use client';
import {useEffect,useRef,useState} from 'react';import {flushSync} from 'react-dom';import type Lenis from 'lenis';
import Plan from '@/components/trame/Plan';import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
const projects=[['Appartement Marais','Paris 3e','2025'],['Loft Bastille','Paris 11e','2024'],['Maison Vincennes','Vincennes','2023'],['Appartement Saint-Germain','Paris 6e','2025'],['Atelier Belleville','Paris 20e','2024'],['Duplex Batignolles','Paris 17e','2023'],['Maison Sceaux','Sceaux','2025'],['Bureau République','Paris 10e','2024'],['Appartement Passy','Paris 16e','2023'],['Galerie Oberkampf','Paris 11e','2025']];
function Trace(){return <svg className="trace" aria-hidden="true" viewBox="0 0 800 500"><path pathLength="1" d="M70 60H730V440H70ZM280 60V240H70M280 350V440M280 350H730M580 60V240H730M40 60V440M70 465H730M440 240V350M380 280H540V320H380Z"/></svg>}
export default function Home(){const [active,setActive]=useState(0),[fading,setFading]=useState(false),[contact,setContact]=useState(false);const root=useRef<HTMLDivElement>(null),lenis=useRef<Lenis|null>(null),busy=useRef(false);useEffect(()=>{let dead=false;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(!reduced)import('lenis').then(({default:Lenis})=>{if(dead)return;lenis.current=new Lenis({autoRaf:true,smoothWheel:true,syncTouch:false,anchors:true})});const projectObserver=new IntersectionObserver(es=>{if(busy.current)return;for(const e of es)if(e.isIntersecting)setActive(Number((e.target as HTMLElement).dataset.index))},{threshold:.55});root.current?.querySelectorAll('.project-screen').forEach(e=>projectObserver.observe(e));const traces=new IntersectionObserver(es=>{es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('drawn');traces.unobserve(e.target)}})},{threshold:.2});root.current?.querySelectorAll('.trace').forEach(e=>traces.observe(e));return()=>{dead=true;lenis.current?.destroy();projectObserver.disconnect();traces.disconnect()}},[]);
async function next(index:number){if(busy.current)return;busy.current=true;const target=root.current?.querySelector<HTMLElement>(`[data-index="${(index+1)%10}"]`);if(!target){busy.current=false;return}const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const small=matchMedia('(max-width: 700px)').matches;const change=()=>{flushSync(()=>setActive((index+1)%10));if(lenis.current)lenis.current.scrollTo(target,{immediate:true,force:true});else target.scrollIntoView({behavior:'instant',block:'start'})};try{const img=target.querySelector('img');if(img&&!img.complete)await Promise.race([img.decode().catch(()=>{}),new Promise(r=>setTimeout(r,900))]);if(!reduced&&!small&&document.startViewTransition){const transition=document.startViewTransition(change);await transition.finished.catch(()=>{});}else if(!reduced){flushSync(()=>setFading(true));await new Promise(r=>setTimeout(r,220));change();await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));setFading(false);await new Promise(r=>setTimeout(r,350))}else change();target.querySelector<HTMLButtonElement>('.project-photo')?.focus({preventScroll:true})}finally{setFading(false);busy.current=false}}
return <div ref={root}><header><a className="logo" href="#">TRAME <span>27</span></a><nav aria-label="Navigation principale"><a href="#studio">Studio</a><a href="#projets">Projets</a><a href="#contact">Contact</a></nav></header><main>
<section className="hero"><span className="eyebrow">STUDIO D'ARCHITECTURE D'INTÉRIEUR</span><h1>Studio Trame 27</h1><p>Architecture d'intérieur. Paris.</p><a className="underlined" href="#projets">Voir les projets <span>↓</span></a><span className="hero-index">PARIS / FRANCE</span></section>
<section id="studio" className="studio editorial"><span className="section-number">01 / STUDIO</span><div><h2>Le silence comme méthode</h2><p>Studio Trame 27 conçoit des intérieurs où chaque élément a une raison d'être là. Pas de superflu, pas de tendance passagère — une grille, des proportions justes, et le blanc comme matière à part entière.</p></div><Trace/></section>
<section id="projets" className={'projects '+(fading?'fading':'')}><div className="projects-intro"><span className="section-number">02 / PROJETS</span><h2>Une photo. Un projet. Rien d'autre.</h2><span>01 — 10</span></div>{projects.map(([name,place,year],i)=><article className={'project-screen '+(i<3?'with-plan':'')} id={'projet-'+(i+1)} key={name} data-index={i} data-active={active===i}><div className="project-meta"><span>{String(i+1).padStart(2,'0')} / 10</span><h3>{name} — {place} · {year}</h3></div><div className="project-layout"><button className="project-photo" onClick={()=>next(i)} aria-label={'Voir le projet suivant après '+name}><img src={'/photos/'+String(i+1).padStart(2,'0')+'.webp'} alt={name+', architecture intérieure en noir et blanc'} loading="lazy" width="1600" height="900"/></button>{i<3&&<Plan index={i}/>}</div><div className="project-bottom"><span>{name}</span><button onClick={()=>next(i)}>{i===9?'Premier projet':'Projet suivant'} <span>↗</span></button></div></article>)}</section>
<section id="approche" className="approach editorial"><span className="section-number">03 / APPROCHE</span><div><h2>Une grille, pas une formule</h2><p>Chaque intérieur est construit sur une trame — un système de proportions qui organise cloisons, ouvertures et mobilier. La grille n'est pas visible dans le résultat final, mais elle est la raison pour laquelle tout semble à sa place.</p></div><Trace/></section>
<section className="press editorial"><span className="section-number">04 / PUBLICATIONS</span><div><h2>Presse</h2><ul><li>AD France, sélection 2025</li><li>Intramuros, portfolio jeunes studios</li><li>Idéat, numéro spécial minimalisme</li></ul></div></section>
<section id="contact" className="contact editorial"><span className="section-number">05 / CONTACT</span><div><h2>Contact</h2><p>Pour un projet résidentiel ou tertiaire.</p><button className="underlined" onClick={()=>setContact(true)}>Nous écrire <span>↗</span></button></div></section>
</main><footer><span>STUDIO TRAME 27</span><p>Concept créé par Megahana — marque fictive à des fins de démonstration.</p><a href="#">Haut de page ↑</a></footer><Dialog open={contact} onOpenChange={setContact}><DialogContent className="contact-dialog"><DialogTitle>Nous écrire</DialogTitle><DialogDescription>Studio Trame 27 est un studio fictif. Aucun message ne peut être envoyé depuis cette démonstration.</DialogDescription><button className="underlined" onClick={()=>setContact(false)}>Revenir au site</button></DialogContent></Dialog></div>}
